name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: golang

    steps:
    - uses: actions/checkout@v4

    - name: Build Program
      run: make
